import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import App from '../src/App';
import * as api from '../src/services/api';

// Mock i18n
vi.mock('../src/i18n', () => ({}));
vi.mock('react-i18next', () => ({
  useTranslation: () => ({
    t: (key: string, opts?: Record<string, unknown>) => {
      const translations: Record<string, string> = {
        title: 'Future Hacker News',
        subtitle: `What will the front page look like in ${opts?.year || '2035'}?`,
        generate: 'Generate',
        generating: 'Generating...',
        errorGenerate: 'Failed to generate stories. Please try again.',
        selectYear: 'Select Year',
        new: 'new',
        past: 'past',
        ask: 'ask',
        show: 'show',
        jobs: 'jobs',
        submit: 'submit',
        login: 'login',
        points: 'points',
        by: 'by',
        comments: 'comments',
        hide: 'hide',
        summary: 'Summary',
        topComments: 'Top Comments',
        loadingDetails: 'Loading details...',
        footer: 'Generated by AI',
        guidelines: 'Guidelines',
        faq: 'FAQ',
        api: 'API',
        security: 'Security',
        lists: 'Lists',
        legal: 'Legal',
        apply: 'Apply to YC',
        contact: 'Contact',
      };
      return translations[key] || key;
    },
    i18n: {
      language: 'en',
      changeLanguage: vi.fn(),
    },
  }),
}));

describe('App', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it('renders the welcome page', () => {
    render(<App />);
    expect(screen.getByText('Future Hacker News')).toBeInTheDocument();
    expect(screen.getByText(/What will the front page look like/)).toBeInTheDocument();
    expect(screen.getByText('Generate →')).toBeInTheDocument();
  });

  it('renders header navigation', () => {
    render(<App />);
    expect(screen.getByText('new')).toBeInTheDocument();
    expect(screen.getByText('past')).toBeInTheDocument();
    expect(screen.getByText('ask')).toBeInTheDocument();
  });

  it('renders footer', () => {
    render(<App />);
    expect(screen.getByText('Generated by AI')).toBeInTheDocument();
    expect(screen.getByText('Guidelines')).toBeInTheDocument();
  });

  it('has year selector with years 2030-2040', () => {
    render(<App />);
    const yearSelect = screen.getByLabelText('Select Year');
    expect(yearSelect).toBeInTheDocument();
    expect(yearSelect.querySelectorAll('option')).toHaveLength(11);
  });

  it('has language selector', () => {
    render(<App />);
    const langSelect = screen.getByLabelText('Language');
    expect(langSelect).toBeInTheDocument();
  });

  it('generates stories when clicking generate button', async () => {
    const mockStories = [
      {
        id: 1,
        title: 'Test Story',
        url: 'https://test.com',
        domain: 'test.com',
        score: 100,
        author: 'testuser',
        time: '2 hours ago',
        comments: 50,
      },
    ];

    vi.spyOn(api, 'generateStories').mockResolvedValue({
      year: 2035,
      stories: mockStories,
    });

    render(<App />);

    // Click the generate button in the welcome area
    fireEvent.click(screen.getByText('Generate →'));

    await waitFor(() => {
      expect(screen.getByText('Test Story')).toBeInTheDocument();
    });

    expect(api.generateStories).toHaveBeenCalledWith(2035, 'en');
  });

  it('shows error on API failure', async () => {
    vi.spyOn(api, 'generateStories').mockRejectedValue(new Error('Network error'));

    render(<App />);
    fireEvent.click(screen.getByText('Generate →'));

    await waitFor(() => {
      expect(screen.getByText('Failed to generate stories. Please try again.')).toBeInTheDocument();
    });
  });

  it('shows loading state while generating', async () => {
    let resolvePromise: (value: api.GenerateResponse) => void;
    const promise = new Promise<api.GenerateResponse>((resolve) => {
      resolvePromise = resolve;
    });

    vi.spyOn(api, 'generateStories').mockReturnValue(promise);

    render(<App />);
    fireEvent.click(screen.getByText('Generate →'));

    expect(screen.getByText('Generating...')).toBeInTheDocument();

    resolvePromise!({ year: 2035, stories: [] });
    await waitFor(() => {
      expect(screen.queryByText('Generating...')).not.toBeInTheDocument();
    });
  });

  it('can change year and generate', async () => {
    const mockStories = [{
      id: 1, title: 'Story 2040', url: 'https://test.com',
      domain: 'test.com', score: 100, author: 'u', time: '1h', comments: 10,
    }];

    vi.spyOn(api, 'generateStories').mockResolvedValue({
      year: 2040,
      stories: mockStories,
    });

    render(<App />);

    const yearSelect = screen.getByLabelText('Select Year');
    fireEvent.change(yearSelect, { target: { value: '2040' } });

    fireEvent.click(screen.getByText('Generate →'));

    await waitFor(() => {
      expect(screen.getByText('Story 2040')).toBeInTheDocument();
    });

    expect(api.generateStories).toHaveBeenCalledWith(2040, 'en');
  });
});
